import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

const CONTRACT_NAME = "ScoreNFT";

// <root>/ScoreNFT/backend
const rel = "../backend";

// <root>/ScoreNFT/frontend/abi
const outdir = path.resolve("./abi");

if (!fs.existsSync(outdir)) {
  fs.mkdirSync(outdir);
}

const dir = path.resolve(rel);
const dirname = path.basename(dir);

const line =
  "\n===================================================================\n";

if (!fs.existsSync(dir)) {
  console.error(
    `${line}Unable to locate ${rel}. Expecting <root>/ScoreNFT/${dirname}${line}`
  );
  process.exit(1);
}

if (!fs.existsSync(outdir)) {
  console.error(`${line}Unable to locate ${outdir}.${line}`);
  process.exit(1);
}

const deploymentsDir = path.join(dir, "deployments");

// Chain configurations: chainName -> { chainId, chainName }
const CHAIN_CONFIGS = {
  localhost: { chainId: 31337, chainName: "localhost" },
  sepolia: { chainId: 11155111, chainName: "sepolia" },
  hardhat: { chainId: 31337, chainName: "hardhat" },
  anvil: { chainId: 31337, chainName: "anvil" },
};

function readDeployment(chainName, chainId, contractName) {
  const chainDeploymentDir = path.join(deploymentsDir, chainName);

  if (!fs.existsSync(chainDeploymentDir)) {
    return undefined;
  }

  const contractFile = path.join(chainDeploymentDir, `${contractName}.json`);
  if (!fs.existsSync(contractFile)) {
    return undefined;
  }

  try {
    const jsonString = fs.readFileSync(contractFile, "utf-8");
    const obj = JSON.parse(jsonString);
    obj.chainId = chainId;
    return obj;
  } catch (error) {
    console.warn(`Warning: Failed to read deployment for ${chainName}: ${error.message}`);
    return undefined;
  }
}

// Auto-detect all available deployments
const deployments = [];
let referenceABI = null;

for (const [chainName, config] of Object.entries(CHAIN_CONFIGS)) {
  const deployment = readDeployment(chainName, config.chainId, CONTRACT_NAME);
  if (deployment) {
    deployments.push({
      chainName,
      chainId: config.chainId,
      displayName: config.chainName,
      address: deployment.address,
      abi: deployment.abi,
    });
    
    // Use first deployment as reference ABI
    if (!referenceABI) {
      referenceABI = deployment.abi;
    }
    
    console.log(`Found deployment on ${chainName} (chainId: ${config.chainId}): ${deployment.address}`);
  } else {
    console.log(`Skipping ${chainName} - no deployment found`);
  }
}

if (deployments.length === 0) {
  console.error(
    `${line}No deployments found! Please deploy at least one contract first.\n\n1. Goto '${dirname}' directory\n2. Run 'npx hardhat deploy --network <network>'.${line}`
  );
  process.exit(1);
}

// Verify all deployments have the same ABI
for (const deployment of deployments) {
  if (JSON.stringify(deployment.abi) !== JSON.stringify(referenceABI)) {
    console.warn(
      `Warning: ABI mismatch detected for ${deployment.chainName}. Using first deployment's ABI.`
    );
  }
}

// Generate ABI file
const abiFile = path.join(outdir, `${CONTRACT_NAME}ABI.ts`);
const abiContent = `// Auto-generated by genabi.mjs
// Do not edit this file manually

export const ${CONTRACT_NAME}ABI = {
  abi: ${JSON.stringify(referenceABI, null, 2)} as const,
};
`;
fs.writeFileSync(abiFile, abiContent, "utf-8");
console.log(`Generated ${abiFile}`);

// Generate Addresses file with all found deployments
const addressEntries = deployments
  .map(
    (deployment) => `  "${deployment.chainId}": {
    address: "${deployment.address}" as \`0x\${string}\`,
    chainId: ${deployment.chainId},
    chainName: "${deployment.displayName}",
  }`
  )
  .join(",\n");

const addressesFile = path.join(outdir, `${CONTRACT_NAME}Addresses.ts`);
const addressesContent = `// Auto-generated by genabi.mjs
// Do not edit this file manually

import { ethers } from "ethers";

export const ${CONTRACT_NAME}Addresses: Record<
  string,
  {
    address: \`0x\${string}\`;
    chainId: number;
    chainName?: string;
  }
> = {
${addressEntries}
};
`;
fs.writeFileSync(addressesFile, addressesContent, "utf-8");
console.log(`Generated ${addressesFile} with ${deployments.length} deployment(s)`);

