// Auto-generated by genabi.mjs
// Do not edit this file manually

import { ethers } from "ethers";

export const ScoreNFTAddresses: Record<
  string,
  {
    address: `0x${string}`;
    chainId: number;
    chainName?: string;
  }
> = {
  "11155111": {
    address: "0xa078702A9Beb78A2B1B7CB049Bf53Be5c8236BdF" as `0x${string}`,
    chainId: 11155111,
    chainName: "sepolia",
  }
};
